"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../shared_components/Layout/Header";
import { ToastProvider } from "../context/ToastContext";
import { Provider } from "react-redux";
import { store } from "../store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 min-h-screen">
        <ToastProvider>
          <Provider store={store}> 
          <Header />
          <main className="p-6">{children}</main>
          </Provider>
        </ToastProvider>

      </body>
    </html>
  );
}
